### PR TITLE
add scanall client

### PR DESCRIPTION
**Pull request by sergimrz**

### CODE REVIEW

**Comment by sergimrz** [comment]
Added scanAll client implementation:
image

Required to handle the schedule of the scan all on Harbor Interrogation Services:
image


I would appreciate if you could review it @elenz97.

**Comment by sergimrz** [comment]
Hello @elenz97, can you take a look to this PR implementing the client to manage the scheduling of scanning all the vulnerabilities?
Adding features is always nice!

**Comment by peresureda** [comment]
HI @elenz97 , can you review this PR ? Thanks!

**Review by elenz97 — APPROVED** [review]
lgtm! thanks for the PR! :+1:

**Pull request merged**
